export {
  SESSION_CONFIG,
  SESSION_CODE_LENGTH,
  SESSION_CODE_PATTERN,
  PARTICIPANT_NAME_MIN_LENGTH,
  PARTICIPANT_NAME_MAX_LENGTH,
  CANVAS_BOUNDS,
  PILE_CAPACITIES
} from './session';

export {
  PARTICIPANT_EMOJIS,
  PARTICIPANT_COLORS,
  getUniqueEmojiAndColor
} from './participants';
